# Install: make pre-commit-install
# See https://pre-commit.com

default_language_version:
  python: python3.10

exclude: |
  (?x)^(
    runs/|
    \.venv/|
    envs/cassie/assets/|
    .*\.(mp4|png|xml|pkl|npz|mjcf|stl|obj)$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
